language: node_js
node_js:
  - 12
cache:
  directories:
    - node_modules
env:
  global:
    - NODE_ENV=test
git:
  depth: 25
  quiet: true
install:
  - npm ci
after_script:
  - npm run report-coverage
  - codecov
script:
  - npm run test
deploy:
  provider: heroku
